

spring.thymeleaf.cache: false
spring.thymeleaf.enabled: true
spring.thymeleaf.prefix:  classpath:/templates/
spring.thymeleaf.suffix:  .html
addon:
  key: TestCrudBoot
  base-url: https://4288e670.ngrok.io

server.port:  8080
spring:  jpa:    database: MYSQL
spring.datasource.driver-class-name:  com.mysql.jdbc.Driver
spring.datasource.url:  jdbc:mysql://acistestdb.ckzign3bwqpl.us-east-2.rds.amazonaws.com:3306/acis?useSSL=false
spring.datasource.username: chakresh
spring.datasource.password: shubham0108

spring.jpa.hibernate.ddl-auto:  create




